services:
  - type: web
    name: extreme-norikae-api
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: extreme-norikae-app
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://extreme-norikae-api.onrender.com/api
